version: '3'

services:
    adv:
        build: ./adv
        ports:
            - 5000:5000
        volumes:
            - ./adv:/app

    postgre:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: docker
            TZ: Europe/Bucharest
            PGTZ: Europe/Bucharest
        volumes:
            - ./postgre/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
            
    mongo:
        image: mongo
        environment:
          MONGO_INITDB_DATABASE: docker
          MONGO_INITDB_ROOT_USERNAME: docker
          MONGO_INITDB_ROOT_PASSWORD: docker
        ports:
            - 27017:27017
          
    frontend:
        build: ./frontend
        ports:
            - 8080:8080
          
    backend:
        build: ./backend
        ports:
            - 12000:12000